export const ADD_RSVP_SUCCESS = 'ADD_RSVP_SUCCESS';
export const ADD_RSVP_FAIL = 'ADD_RSVP_FAIL';
export const DELETE_RSVP_SUCCESS = 'DELETE_RSVP_SUCCESS';
export const DELETE_RSVP_FAIL = 'DELETE_RSVP_FAIL';
export const GET_USER_RSVPS_SUCCESS = 'GET_USER_RSVPS_SUCCESS';
export const GET_USER_RSVPS_FAIL = 'GET_USER_RSVPS_FAIL';
